# - Find GSL
# Find the GNU Scientific Library (GSL) includes and library
#
# This module defines
#  GSL_FOUND
#  GSL_LIBRARIES
#  GSL_INCLUDE_DIR
#

FIND_PATH(GSL_INCLUDE_DIR gsl/gsl_rng.h
  /usr/local/include
  /usr/include
)

FIND_LIBRARY(GSL_LIBRARY NAMES gsl)

FIND_LIBRARY(GSL_CBLAS_LIBRARY NAMES gslcblas)

IF(GSL_LIBRARY AND GSL_CBLAS_LIBRARY AND GSL_INCLUDE_DIR)
  SET(GSL_LIBRARIES ${GSL_LIBRARY} ${GSL_CBLAS_LIBRARY})
  SET(GSL_FOUND "YES")
ELSE(GSL_LIBRARY AND GSL_CBLAS_LIBRARY AND GSL_INCLUDE_DIR)
  SET(GSL_FOUND "NO")
ENDIF(GSL_LIBRARY AND GSL_CBLAS_LIBRARY AND GSL_INCLUDE_DIR)

IF(GSL_FOUND)
  IF(NOT GSL_FIND_QUIETLY)
    MESSAGE(STATUS "Found GNU Scientific Library: ${GSL_LIBRARIES}")
  ENDIF(NOT GSL_FIND_QUIETLY)
ELSE(GSL_FOUND)
  IF(GSL_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find GNU Scientific Library")
  ENDIF(GSL_FIND_REQUIRED)
ENDIF(GSL_FOUND)

MARK_AS_ADVANCED(
  GSL_LIBRARY
  GSL_CBLAS_LIBRARY
  GSL_INCLUDE_DIR
)
