#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# mdparam - list simulation parameters in HDF5 data file
#
# Copyright (C) 2008  Peter Colberg
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os, sys, os.path
import argparse
import pager
import sets
import tables
from numpy import *

# HDF5 parameter descriptions
param_name = {
    'correlation': {
        'block_count':  'block count',
        'block_shift':  'block shift',
        'block_size':   'block size',
        'max_samples':  'maximum samples per block',
        'q_values':     'q-values in Fourier transform',
        'sample_rate':  'sample rate',
        'steps':        'total simulation steps',
        'time':         'total simulation time',
    },
    'mdsim': {
        'blocks':               'CUDA blocks',
        'box_length':           'periodic box length',
        'cell_length':          'cell length',
        'cell_occupancy':       'average cell occupancy',
        'cells':                'cells per dimension',
        'cutoff_radius':        'potential cutoff radius',
        'density':              'density',
        'dimension':            'dimensions',
        'neighbours':           'neighbour list placeholders',
        'particles':            'particles',
        'placeholders':         'cell list placeholders',
        'threads':              'CUDA threads',
        'timestep':             'timestep',
    },
    'program': {
        'name':         'name',
        'variant':      'variant',
        'version':      'version',
    },
}


# parse command line arguments
parser = argparse.ArgumentParser(prog='mdparam')
parser.add_argument('input', nargs='+', help='HDF5 simulation data file')
args = parser.parse_args()

# read parameters from HDF5 files
data = {}
for i, fn in enumerate(args.input):
    try:
        f = tables.openFile(fn, mode='r')
    except IOError:
        raise SystemExit('failed to open HDF5 file: %s' % fn)

    try:
        for node in f.root.param:
            group = node._v_name
            if not group in data:
                data[group] = {}

            for param in node._v_attrs._f_list():
                if not param in data[group]:
                    data[group][param] = [None] * len(args.input)
                data[group][param][i] = node._v_attrs.__getattr__(param)

    except tables.exceptions.NoSuchNodeError:
        raise SystemExit('missing simulation data in file: %s' % fn)

    f.close()

# page output if longer than screen
pager.setup_pager()

# display parameters with colored output
for group, params in sorted(data.items(), key=lambda x: x[0]):
    # group title
    s = u'%s[%s]%s\n' % ('\x1b[1;31m', group, '\x1b[0m')
    for name, values in sorted(params.items(), key=lambda x: param_name[group][x[0]]):
        # parameter name
        s += u' • %s%s%s:' % ('\x1b[1;34m', param_name[group][name], '\x1b[0m')
        if len(sets.Set(values)) == 1:
            # common parameter value for all data sets
            s += ' %s\n' % str(values[0])
        else:
            # different parameter values
            s += '\n'
            for i, value in enumerate(values):
                s += u'    %s %s[%s]%s\n' % (str(value), '\x1b[36m', args.input[i], '\x1b[0m')
    print s

