# - Find NetCDF
# Find the NetCDF (network Common Data Form) includes and library
#
# This module defines
#  NetCDF_FOUND
#  NetCDF_INCLUDE_DIR
#  NetCDF_LIBRARY
#  NetCDF_CPP_LIBRARY
#  NetCDF_FORTRAN_LIBRARY
#

FIND_PATH(NetCDF_INCLUDE_DIR netcdf.h
  /usr/local/include
  /usr/include
)

FIND_LIBRARY(NetCDF_LIBRARY NAMES netcdf)
FIND_LIBRARY(NetCDF_CPP_LIBRARY NAMES netcdf_c++)
FIND_LIBRARY(NetCDF_FORTRAN_LIBRARY NAMES netcdff)

IF(NetCDF_LIBRARY AND NetCDF_CPP_LIBRARY AND NetCDF_FORTRAN_LIBRARY AND NetCDF_INCLUDE_DIR)
  SET(NetCDF_FOUND "YES")
ELSE(NetCDF_LIBRARY AND NetCDF_CPP_LIBRARY AND NetCDF_FORTRAN_LIBRARY AND NetCDF_INCLUDE_DIR)
  SET(NetCDF_FOUND "NO")
ENDIF(NetCDF_LIBRARY AND NetCDF_CPP_LIBRARY AND NetCDF_FORTRAN_LIBRARY AND NetCDF_INCLUDE_DIR)

IF(NetCDF_FOUND)
  IF(NOT NetCDF_FIND_QUIETLY)
    MESSAGE(STATUS "Found NetCDF: ${NetCDF_LIBRARIES}")
  ENDIF(NOT NetCDF_FIND_QUIETLY)
ELSE(NetCDF_FOUND)
  IF(NetCDF_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find NetCDF")
  ENDIF(NetCDF_FIND_REQUIRED)
ENDIF(NetCDF_FOUND)

MARK_AS_ADVANCED(
  NetCDF_LIBRARY
  NetCDF_CPP_LIBRARY
  NetCDF_FORTRAN_LIBRARY
  NetCDF_INCLUDE_DIR
)
